### ISSUE TITLE
Handle Strange PDFs that cannot be printed

### ISSUE THREAD

**Issue by andrewtedi** [SCE-Development/Clark#1032]
Encrypted PDFs can be uploaded, but currently, the wrong error prompt is returned on the frontend. 
![image](https://user-images.githubusercontent.com/40414974/158272678-8a973d19-1c48-4297-8725-f309df7cc571.png)
The error message should show what is seen in this catch statement.
[![image](https://user-images.githubusercontent.com/40414974/158272797-cad15704-1c87-430a-8927-7ed5017a373e.png)
](https://github.com/SCE-Development/Core-v4/blob/165f9530b6ab08df46034c4cf9f637d8f6b6dd8e/src/Pages/2DPrinting/2DPrinting.js#L119)

**Comment by evanugarte** [comment]
closed by #1430
