### ISSUE TITLE
Windows set up

### ISSUE THREAD

**Issue by Luceium** [SCE-Development/Clark#1241]
On the set up steps windows users have half of their json file missing.
There is an easy known fix: undo the deletion with the git tool on vscode

I will go back and update this issue with more specific details later.

**Comment by danknessdra** [comment]
cool guy mau

**Comment by evanugarte** [comment]
what do you mean by this

**Comment by Luceium** [comment]
When a Windows developer follows the wiki instructions, at some point half of one of the config files gets deleted.

**Comment by evanugarte** [comment]
no
