### ISSUE TITLE
Cleezy (URL Shortener) Table Improvements

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Clark#1363]
lets follow the format of the user manager page https://github.com/SCE-Development/Clark/blob/a8ce677097931bbcf1b7f9dab4d7722d814b127b/src/Pages/Overview/Overview.js#L23

where we update the url shortener table to have:
1. Add a color gradient to the table background
2. Combine the URL and alias into one link (the alias is a blue link which opens the shortened url in a new tab)
3. Add a column in the UI to show when the url was created (the Cleezy API already returns this date)
4. Remove the text "List of URLs:" from the admin url shortner page

Example UI is below:
<img width="1063" alt="image" src="https://github.com/SCE-Development/Clark/assets/36345325/b0580d47-9cce-4c53-ac43-7f45f197bc0c">

**Comment by evanugarte** [comment]
@gursheyss will work on this with another intern/dev member

**Comment by pnavab** [comment]
resolved by #1371
