### ISSUE TITLE
No SEO on home page

### ISSUE THREAD

**Issue by joshua-demo** [SCE-Development/Clark#1366]
![image](https://github.com/SCE-Development/Clark/assets/116464215/b7ceaee2-47e0-4f87-8624-97f9d34b9d6a)

**Comment by evanugarte** [comment]
do you wanna work on this idk how to do it

**Comment by danknessdra** [comment]
More context: 
![image](https://github.com/SCE-Development/Clark/assets/73515552/8a5c8771-0b4c-496a-b69e-1a44c2caaeff)
SCE shows up with a description that Google parses, while we could have a more detailed description like this image:
![image](https://github.com/SCE-Development/Clark/assets/73515552/61b69088-a736-4aa2-8271-d86b47236bef)

This can probably be done with meta tags in the index html file.

**Comment by evanugarte** [comment]
if you look up "sce sjsu" we are first on many search engines
