### ISSUE TITLE
Add Column for # of Times URL is Used for Url Shortener Pg

### ISSUE THREAD

**Issue by syng828** [SCE-Development/Clark#1386]
## show the amount of times a url was visited on the shortener page
now that https://github.com/SCE-Development/cleezy/pull/30 is merged, we should show the
 value of this column on the club website admin dashboard

### game plan
- [x] run cleezy locally on your computer
- [x] run clark locally on your computer
- [x] make some urls locally, follow the readme in the cleezy project
- [x] make sure you can sign in and visit the url shortener page locally
- [x] find the location in clark where we call the cleezy `/list` endpoint
- [x] add a new column in `src/Pages/URLShortener/URLShortener.js` to view the number of times a url was used

**Comment by evanugarte** [comment]
resolved with #1387
