### ISSUE TITLE
Add search options for email and last name

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Clark#186]
Add search options for email and last name on the src/Pages/Overview/Overview

note:
```js
state.users: holds all users from data base
state.query: holds search values
state.queryResults: holds filtered users from query
```

-Evan-
Replace the ```<input>``` in Overview
https://github.com/SCE-Development/Core-v4/pull/178#discussion_r362354086

**Comment by ThaiQ** [comment]
@evanugarte I've done this before. You can enter first name, last name, or email of the user. You don't need to tell it which field it should be searching for. [The code is here](https://github.com/SCE-Development/Core-v4/blob/fe1b1d56d8bffd86e5a41425bdb11fa59bf0bded/src/Pages/Overview/Overview.js#L54)

I'm closing this brono

**Comment by evanugarte** [comment]
@ThaiQ Reopened this as we should be able to search for user's by category (1 semester membership, 1 year membership, officers, expired users, etc.). Can you add a dropdown on the page that allows us to search by these categories?

**Comment by ThaiQ** [comment]
@evanugarte If you want to search for membership, and/or expired user, then I think we should just add into the current drop-down. because the current search is already for firstName or lastName or email already

**Comment by evanugarte** [comment]
this was added with #1343
