### ISSUE TITLE
Add Google Calendar API to Create and Attend Events

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Clark#216]
Similar to this photo:
![image](https://user-images.githubusercontent.com/36345325/72223546-dbbe5480-3524-11ea-928b-ea26710cfb22.png)

We should have an Attend button that when clicked, invites a user to the event through Google Calendar. We can use the [Calendar API](https://developers.google.com/calendar) to accomplish this.

Furthermore, when an officer creates an event, a calendar event should be created with the sce.sjsu@gmail.com email.

I will take on this issue after #127 is finished.

**Comment by william-green** [comment]
I can take this.

**Comment by evanugarte** [comment]
### 1/28 Meeting
#### Before connecting APIs to website
1. We need to add an optional Google Calendar Event URL to [the existing Event Schema](https://github.com/SCE-Development/Core-v4/blob/dev/api/models/Event.js)
```js
googleCalendarUrl: {
      type: String
    },
```
2. add an endpoint to the API in [Event.js](https://github.com/SCE-Development/Core-v4/blob/de0035627e0e905823d3e488a9d31673b0760d52/api/routes/Event.js#L18)
```js
router.get('/generateCalendarLink', (req, res) => {
  // do ur stuff here
})
```
3. add a function in [APIFunctions/Event.js](https://github.com/SCE-Development/Core-v4/blob/dev/src/APIFunctions/Event.js)
```js
export async function generateCalendarLink (eventToAdd) {
  // call on API here
}
```

#### Writing the Endpoint
- Similar to [this example](https://developers.google.com/calendar/create-events?apix_params=%7B%22calendarId%22%3A%22primary%22%2C%22resource%22%3A%7B%22end%22%3A%7B%22dateTime%22%3A%222015-05-28T09%3A00%3A00-07%3A00%22%7D%2C%22start%22%3A%7B%22dateTime%22%3A%222015-05-28T09%3A00%3A00-03%3A00%22%7D%7D%7D#metadata) call on the calendar API
- Similar to the [/createEvent endpoint](https://github.com/SCE-Development/Core-v4/blob/de0035627e0e905823d3e488a9d31673b0760d52/api/routes/Event.js#L24), send the entire event object over.

#### Calling on Endpoint from APIFunctions
- The `eventToAdd` parameter should contain all of the relevant event data

#### Calling it from the Fronteend
- [This line of code](https://github.com/SCE-Development/Core-v4/blob/de0035627e0e905823d3e488a9d31673b0760d52/src/Pages/EventManager/EventManager.js#L46) creates a new event.
- Within that `if` block, grab the calendar URL, then add it to the event object. kinda like this:
```js
 if (modalState === eventModalState.SUBMIT) {
      // grab the url
      const googleCalendarUrl = await generateCalendarLink(event)
      // assign it to the event object here

      // add it to the new event
      await createNewEvent(event, props.user.token)
 }
```
