### ISSUE TITLE
Inventory Dashboard (UI)

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Clark#284]
1. Make a folder under ```src/Pages``` calls ```inventory```
2. create ```inventory.js```
3. Make dashboard follow [Evan](https://github.com/evanugarte/InventoryEcho)

**Comment by evanugarte** [comment]
@ThaiQ the description of this is super vague and doesn't offer much help to the assignee. Let's schedule a time to meet to write all of these issues out

**Comment by aashrav** [comment]
@evanugarte Yeah, no concrete plan. We are probably following your github.

**Comment by ThaiQ** [comment]
This issue is in developing. I don't understand the layout of your project so i couldn't write too much. Assh is working on something else currently.
