### ISSUE TITLE
Get user from email in mongo

### ISSUE THREAD

**Issue by jeffersonly** [SCE-Development/Clark#404]
Create a function that takes in an email as a parameter and returns the user in mongodb

This function will be within the src/APIFunctions folder
Use axios to do a get request -> write the function

**Comment by jeffersonly** [comment]
@ThaiQ 
It looks like there is already a function that does the APIFunctions user class, found [here](https://github.com/SCE-Development/Core-v4/blob/dev/src/APIFunctions/User.js)

`export async function searchUserByEmail(email, token) {
  let status = new UserApiResponse();
  await axios
    .post('/api/user/search', {
      token,
      email
    })
    .then(result => {
      status.responseData = result.data;
    })
    .catch(() => {
      status.error = true;
    });
  return status;
}`

**Comment by evanugarte** [comment]
@ThaiQ are we still doing this

**Comment by evanugarte** [comment]
closing because #1172 did this
