### ISSUE TITLE
Event Creation Error

### ISSUE THREAD

**Issue by quinlanhnguyen** [SCE-Development/Clark#536]
When creating an event in the event manager, if you type the parameters in random order, it won't let you create the event. However, if you enter the information from left to right you can create the event.

![image](https://user-images.githubusercontent.com/67393572/86619992-692caf80-bf70-11ea-85a6-646380778bda.png)
When information is entered in random order

![image](https://user-images.githubusercontent.com/67393572/86620135-b01aa500-bf70-11ea-8014-6707c56f6113.png)
When information is entered in correct order

**Comment by evanugarte** [comment]
events on the website are no longer a thing
