### ISSUE TITLE
Google API getEventsFromCalendar bug

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/Clark#699]
getEventsFromCalendar is getting an error of not enough permissions. The reason is because the oAuth2 token is incorrectly generated/used. 

Below, it shows that the scope of the token is `mail.google.com`. It should be `https://www.googleapis.com/auth/calendar`.

![image](https://user-images.githubusercontent.com/26675745/99161482-b996e500-26a7-11eb-880d-11094ed037d0.png)

**Comment by evanugarte** [comment]
we dont use g calendar anymore
