### ISSUE TITLE
Migrating images in public to S3

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Clark#731]
https://github.com/SCE-Development/Core-v4/tree/dev/public/images

@IsitaB @aashrav

**Comment by evanugarte** [comment]
- With uploading any photo, we should not store this locally, but instead on a aws S3
- Any and all images can be rendered by calling on APIs from Google.
- Same with `.stl` files for the 3d console

**Comment by evanugarte** [comment]
github cdn ftw
