### ISSUE TITLE
SP22 Blasts

### ISSUE THREAD

**Issue by au01gh** [SCE-Development/Clark#986]

**Comment by allen-tran** [comment]
u are so hot 😍 @au01gh

**Comment by au01gh** [comment]
![Game Night 2](https://user-images.githubusercontent.com/59246763/153791546-8e9bb295-095c-4cd7-80a2-6df455d3051a.png)

**Comment by au01gh** [comment]
> u are so hot 😍 @au01gh
Sir, this is an eblast issue.
